apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '4'
  labels:
    app: cp-ksql-server
  name: cp-ksql-server
  namespace: strimzi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cp-ksql-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: '5556'
        prometheus.io/scrape: 'true'
      creationTimestamp: null
      labels:
        app: cp-ksql-server
    spec:
      containers:
        - env:
            - name: KSQL_BOOTSTRAP_SERVERS
              value: 'PLAINTEXT://dkv-kafka-kafka-brokers:9092'
            - name: KSQL_KSQL_SERVICE_ID
              value: fancy-camel
            - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
              value: 'http://cp-schema-registry:8081'
            - name: KSQL_LISTENERS
              value: 'http://0.0.0.0:8088'
            - name: KSQL_JMX_PORT
              value: '5555'
          image: 'kubernautslabs/cp-ksql-server:5.0.1'
          imagePullPolicy: IfNotPresent
          name: cp-ksql-server
          ports:
            - containerPort: 8088
              name: server
              protocol: TCP
            - containerPort: 5555
              name: jmx
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30